# Generated by Django 4.0 on 2022-01-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(default=1, upload_to='animes'),
            preserve_default=False,
        ),
    ]
