# Generated by Django 4.0 on 2022-01-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email'),
        ('video', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='account.user'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('rating', 'user')},
        ),
    ]
