# Generated by Django 4.0 on 2022-01-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_topp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topp',
        ),
    ]
